import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import cineBoleto from "../app/_lotties/cine-boleto.json";
import { ConfigStoreProvider } from "./_providers/config-store-provider";
import {
  getTmdbConfiguration,
  TmdbConfigDetails,
} from "./_services/tmdb/configuration";
import LottiePlayer from "./_components/lottiePlayer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const configRes = await getTmdbConfiguration({ which: "details" });
  const configData = (await configRes.json()) as TmdbConfigDetails;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex gap-2 text-3xl items-center p-4">
          <LottiePlayer size={50} alternatelyLoop lottieJson={cineBoleto} />
          <h1>Movies</h1>
        </header>
        <ConfigStoreProvider value={configData}>{children}</ConfigStoreProvider>
      </body>
    </html>
  );
}
